typedef enum {NONE=0, IDENT, NUMBER,
		BEGIN, CALL, CONST, DO,  ELSE, END, FOR, IF, ODD,
		PROCEDURE, PROGRAM, THEN, TO, VAR, WHILE,
		
		PLUS, MINUS, TIMES, SLASH, EQU, NEQ, LSS, LEQ,GTR, GEQ, PERCENT,
		LPARENT, RPARENT, LBRACK,RBRACK,PERIOD,COMMA,SEMICOLON, ASSIGN
} TokenType;
